### ISSUE TITLE
Email form isn't working?

### ISSUE THREAD

**Issue by albertchae** [hackclub/hackathons#148]
According to @maxwofford, this form isn't working. This issue is to investigate and fix

EDIT: Thanks to @exu3 , form saves data to hackclub/api DB but since events are in Airtable, the event notification email doesn't work

<img width="631" alt="image" src="https://user-images.githubusercontent.com/217050/178162098-fff86436-98ff-4bbf-99cf-2b8cf1996b90.png">

**Comment by exu3** [comment]
The form itself works, but the data gets added to the old https://github.com/hackclub/api database which was deprecated in favor of Airtable. 

Since new events are added to Airtable (not hackclub/api), the [event notification email](https://github.com/hackclub/api/blob/master/spec/mailers/event_email_subscriber_spec.rb) itself is also currently out of commission.

**Comment by albertchae** [comment]
Thanks @exu3 I think that's actually what he said and I misremembered. I'll edit the issue to match your details

**Comment by exu3** [comment]
Closed by #163
